//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jewellery_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoicereport
    {
        public int odetail_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string mname { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string name { get; set; }
        public string Expr1 { get; set; }
        public Nullable<System.DateTime> deliverydate { get; set; }
        public string Expr2 { get; set; }
        public Nullable<System.DateTime> DOC { get; set; }
        public Nullable<decimal> grandtotal { get; set; }
        public string paymentmode { get; set; }
        public Nullable<int> p_id { get; set; }
        public string Expr3 { get; set; }
        public string price { get; set; }
        public int quantity { get; set; }
        public decimal total { get; set; }
    }
}
