//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jewellery_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_feedback
    {
        public int f_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string comment { get; set; }
        public System.DateTime DOC { get; set; }
    }
}
