//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jewellery_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_order
    {
        public int order_id { get; set; }
        public int user_id { get; set; }
        public string status { get; set; }
        public System.DateTime deliverydate { get; set; }
        public string paymentmode { get; set; }
        public string address { get; set; }
        public decimal grandtotal { get; set; }
        public System.DateTime DOC { get; set; }
        public System.DateTime DOM { get; set; }
    }
}
