//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jewellery_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orderdetails
    {
        public int odetail_id { get; set; }
        public int order_id { get; set; }
        public int p_id { get; set; }
        public int quantity { get; set; }
        public decimal total { get; set; }
    }
}
