//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jewellery_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment
    {
        public int card_id { get; set; }
        public int order_id { get; set; }
        public string name_on_card { get; set; }
        public string card_no { get; set; }
        public string card_exp { get; set; }
        public int cvv { get; set; }
        public decimal amount { get; set; }
        public string confirmation { get; set; }
        public System.DateTime DOC { get; set; }
    }
}
