//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jewellery_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int p_id { get; set; }
        public int cat_id { get; set; }
        public int col_id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public int color { get; set; }
        public string size { get; set; }
        public string description { get; set; }
        public string offer { get; set; }
        public string image { get; set; }
        public System.DateTime DOC { get; set; }
        public System.DateTime DOM { get; set; }
    }
}
