//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jewellery_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempdata
    {
        public int temp_id { get; set; }
        public int user_id { get; set; }
        public int order_id { get; set; }
        public string date { get; set; }
    }
}
